### PR TITLE
Upgrade Prometheus client to v1.0.0

### PR DESCRIPTION
**Pull request by hairyhenderson**
Upgrading to client_golang v1.0.0!

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by hairyhenderson** [comment]
There are 2 CI failures:
- one against `master` which was pre-existing
- one against `1.11`, which is due to @beorn7's `perks` package requiring Go 1.12 - @povilasv would it make sense to remove support in CI for 1.11?

**Comment by beorn7** [comment]
https://github.com/beorn7/perks doesn't really requile Go 1.12. That slipped in when it was moved to Go modules. I'll lower that to Go 1.11. (It would also work with much earlier versions, but they don't have Go module support.)

**Comment by beorn7** [comment]
Could you re-run the CI job? It should work now…

**Comment by hairyhenderson** [comment]
Thanks @beorn7!

**Comment by hairyhenderson** [comment]
Ok, looks like the `1.11` CI job is passing now. `master` is still failing, but that's pre-existing.

PTAL @povilasv 😉

**Comment by povilasv** [comment]
LGTM! thanks for doing this ;)

I'll remove the test on go master

**Comment by hairyhenderson** [comment]
Thanks for merging @povilasv 😬

**Pull request merged**
